/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *  - ITEMS: gross discount items amount.
 *  - ITEMS_DISCOUNTED: discounted items amount.
 *  - DISCOUNT: discount amount. It is a NEGATIVE amount.
 * @export
 */
export const OrderDataSubtotalCode = {
    Unknown: 'UNKNOWN',
    Payment: 'PAYMENT',
    Shipment: 'SHIPMENT',
    Tax: 'TAX',
    Items: 'ITEMS',
    ItemsDiscounted: 'ITEMS_DISCOUNTED',
    Discount: 'DISCOUNT'
} as const;
export type OrderDataSubtotalCode = typeof OrderDataSubtotalCode[keyof typeof OrderDataSubtotalCode];


export function OrderDataSubtotalCodeFromJSON(json: any): OrderDataSubtotalCode {
    return OrderDataSubtotalCodeFromJSONTyped(json, false);
}

export function OrderDataSubtotalCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDataSubtotalCode {
    return json as OrderDataSubtotalCode;
}

export function OrderDataSubtotalCodeToJSON(value?: OrderDataSubtotalCode | null): any {
    return value as any;
}

