/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderDataTotalCode = {
    Unknown: 'UNKNOWN',
    Ordered: 'ORDERED',
    Paid: 'PAID',
    Refunded: 'REFUNDED'
} as const;
export type OrderDataTotalCode = typeof OrderDataTotalCode[keyof typeof OrderDataTotalCode];


export function OrderDataTotalCodeFromJSON(json: any): OrderDataTotalCode {
    return OrderDataTotalCodeFromJSONTyped(json, false);
}

export function OrderDataTotalCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDataTotalCode {
    return json as OrderDataTotalCode;
}

export function OrderDataTotalCodeToJSON(value?: OrderDataTotalCode | null): any {
    return value as any;
}

