/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface RmaAddNoteRequest
 */
export interface RmaAddNoteRequest {
    /**
     * 
     * @type {string}
     * @memberof RmaAddNoteRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof RmaAddNoteRequest
     */
    'returnId': string;
    /**
     * 
     * @type {string}
     * @memberof RmaAddNoteRequest
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof RmaAddNoteRequest
     */
    'note': string;
}
