/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface RmaCustomerInfo
 */
export interface RmaCustomerInfo {
    /**
     * 
     * @type {string}
     * @memberof RmaCustomerInfo
     */
    'firstname'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaCustomerInfo
     */
    'lastname'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaCustomerInfo
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaCustomerInfo
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaCustomerInfo
     */
    'grn'?: string;
}
