/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface RmaCreateReturnRequest
 */
export interface RmaCreateReturnRequest {
    /**
     * 
     * @type {string}
     * @memberof RmaCreateReturnRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof RmaCreateReturnRequest
     */
    'orderGrn': string;
    /**
     * 
     * @type {Array<CreateReturnRequestProduct>}
     * @memberof RmaCreateReturnRequest
     */
    'products': Array<CreateReturnRequestProduct>;
    /**
     * 
     * @type {RmaRefundMethod}
     * @memberof RmaCreateReturnRequest
     */
    'preferredRefundMethod': RmaRefundMethod;
    /**
     * 
     * @type {boolean}
     * @memberof RmaCreateReturnRequest
     */
    'refundShippingCost'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RmaCreateReturnRequest
     */
    'refundPaymentCost'?: boolean;
    /**
     * 
     * @type {RmaCustomerInfo}
     * @memberof RmaCreateReturnRequest
     */
    'customerInfo'?: RmaCustomerInfo;
    /**
     * 
     * @type {RmaPostalAddress}
     * @memberof RmaCreateReturnRequest
     */
    'returnAddress'?: RmaPostalAddress;
    /**
     * 
     * @type {string}
     * @memberof RmaCreateReturnRequest
     */
    'note'?: string;
}
