/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RmaListNotesByReturnIdRequestSortSortField = {
    Unknown: 'UNKNOWN',
    Date: 'DATE'
} as const;
export type RmaListNotesByReturnIdRequestSortSortField = typeof RmaListNotesByReturnIdRequestSortSortField[keyof typeof RmaListNotesByReturnIdRequestSortSortField];


export function RmaListNotesByReturnIdRequestSortSortFieldFromJSON(json: any): RmaListNotesByReturnIdRequestSortSortField {
    return RmaListNotesByReturnIdRequestSortSortFieldFromJSONTyped(json, false);
}

export function RmaListNotesByReturnIdRequestSortSortFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): RmaListNotesByReturnIdRequestSortSortField {
    return json as RmaListNotesByReturnIdRequestSortSortField;
}

export function RmaListNotesByReturnIdRequestSortSortFieldToJSON(value?: RmaListNotesByReturnIdRequestSortSortField | null): any {
    return value as any;
}

