/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface RmaListNotesByReturnIdRequestSort
 */
export interface RmaListNotesByReturnIdRequestSort {
    /**
     * evaluation_order is the order in which the sort will be applied. The lower the number, the earlier the sort will be applied.
     * @type {number}
     * @memberof RmaListNotesByReturnIdRequestSort
     */
    'evaluationOrder': number;
    /**
     * 
     * @type {RmaListNotesByReturnIdRequestSortSortField}
     * @memberof RmaListNotesByReturnIdRequestSort
     */
    'field': RmaListNotesByReturnIdRequestSortSortField;
    /**
     * 
     * @type {RmaSortOrder}
     * @memberof RmaListNotesByReturnIdRequestSort
     */
    'order'?: RmaSortOrder;
}
