/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface RmaNoteResponse
 */
export interface RmaNoteResponse {
    /**
     * 
     * @type {string}
     * @memberof RmaNoteResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaNoteResponse
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaNoteResponse
     */
    'author'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaNoteResponse
     */
    'note'?: string;
    /**
     * 
     * @type {Date}
     * @memberof RmaNoteResponse
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RmaNoteResponse
     */
    'updatedAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RmaNoteResponse
     */
    'deletedAt'?: Date;
}
