/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface RmaOrderDataItem
 */
export interface RmaOrderDataItem {
    /**
     * 
     * @type {string}
     * @memberof RmaOrderDataItem
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaOrderDataItem
     */
    'productGrn'?: string;
    /**
     * 
     * @type {number}
     * @memberof RmaOrderDataItem
     */
    'qtyOrdered'?: number;
    /**
     * 
     * @type {number}
     * @memberof RmaOrderDataItem
     */
    'qtyCommitted'?: number;
    /**
     * 
     * @type {number}
     * @memberof RmaOrderDataItem
     */
    'qtyShipped'?: number;
    /**
     * 
     * @type {RmaMoney}
     * @memberof RmaOrderDataItem
     */
    'unitSalePrice'?: RmaMoney;
    /**
     * 
     * @type {RmaMoney}
     * @memberof RmaOrderDataItem
     */
    'unitListPrice'?: RmaMoney;
    /**
     * 
     * @type {RmaMoney}
     * @memberof RmaOrderDataItem
     */
    'unitVatAmount'?: RmaMoney;
    /**
     * 
     * @type {RmaMoney}
     * @memberof RmaOrderDataItem
     */
    'rowSalePrice'?: RmaMoney;
    /**
     * 
     * @type {RmaMoney}
     * @memberof RmaOrderDataItem
     */
    'rowListPrice'?: RmaMoney;
    /**
     * 
     * @type {RmaMoney}
     * @memberof RmaOrderDataItem
     */
    'rowVatAmount'?: RmaMoney;
    /**
     * 
     * @type {number}
     * @memberof RmaOrderDataItem
     */
    'vatPercentage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RmaOrderDataItem
     */
    'vatInaccurate'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RmaOrderDataItem
     */
    'vatCalculated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RmaOrderDataItem
     */
    'productName'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaOrderDataItem
     */
    'productCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaOrderDataItem
     */
    'productSku'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaOrderDataItem
     */
    'productOptions'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaOrderDataItem
     */
    'productImg'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaOrderDataItem
     */
    'productData'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaOrderDataItem
     */
    'shipmentInfoReference'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RmaOrderDataItem
     */
    'promotionGrn'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof RmaOrderDataItem
     */
    'productIsVirtual'?: boolean;
}
