/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface RmaReturnResponse
 */
export interface RmaReturnResponse {
    /**
     * 
     * @type {string}
     * @memberof RmaReturnResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaReturnResponse
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaReturnResponse
     */
    'orderGrn'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaReturnResponse
     */
    'status'?: string;
    /**
     * 
     * @type {Array<RmaReturnProduct>}
     * @memberof RmaReturnResponse
     */
    'products'?: Array<RmaReturnProduct>;
    /**
     * 
     * @type {RmaRefundMethod}
     * @memberof RmaReturnResponse
     */
    'preferredRefundMethod'?: RmaRefundMethod;
    /**
     * 
     * @type {boolean}
     * @memberof RmaReturnResponse
     */
    'refundShippingCost'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RmaReturnResponse
     */
    'refundPaymentCost'?: boolean;
    /**
     * 
     * @type {RmaCustomerInfo}
     * @memberof RmaReturnResponse
     */
    'customerInfo'?: RmaCustomerInfo;
    /**
     * 
     * @type {RmaPostalAddress}
     * @memberof RmaReturnResponse
     */
    'returnAddress'?: RmaPostalAddress;
    /**
     * 
     * @type {string}
     * @memberof RmaReturnResponse
     */
    'note'?: string;
    /**
     * 
     * @type {Array<RmaReturnHistory>}
     * @memberof RmaReturnResponse
     */
    'history'?: Array<RmaReturnHistory>;
    /**
     * 
     * @type {Date}
     * @memberof RmaReturnResponse
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RmaReturnResponse
     */
    'updatedAt'?: Date;
    /**
     * 
     * @type {RmaOrderData}
     * @memberof RmaReturnResponse
     */
    'orderData'?: RmaOrderData;
}
