/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface RmaReturnProduct
 */
export interface RmaReturnProduct {
    /**
     * 
     * @type {string}
     * @memberof RmaReturnProduct
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof RmaReturnProduct
     */
    'reason'?: string;
    /**
     * 
     * @type {RmaReturnProductProperty}
     * @memberof RmaReturnProduct
     */
    'requested'?: RmaReturnProductProperty;
    /**
     * 
     * @type {RmaReturnProductProperty}
     * @memberof RmaReturnProduct
     */
    'approved'?: RmaReturnProductProperty;
    /**
     * 
     * @type {RmaReturnProductProperty}
     * @memberof RmaReturnProduct
     */
    'verified'?: RmaReturnProductProperty;
    /**
     * 
     * @type {RmaReturnProductProperty}
     * @memberof RmaReturnProduct
     */
    'refunded'?: RmaReturnProductProperty;
}
