/* tslint:disable */
/* eslint-disable */
/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RmaRefundMethod = {
    Unknown: 'REFUND_METHOD_UNKNOWN',
    Offline: 'REFUND_METHOD_OFFLINE',
    Coupon: 'REFUND_METHOD_COUPON',
    SameAsPayment: 'REFUND_METHOD_SAME_AS_PAYMENT'
} as const;
export type RmaRefundMethod = typeof RmaRefundMethod[keyof typeof RmaRefundMethod];


export function RmaRefundMethodFromJSON(json: any): RmaRefundMethod {
    return RmaRefundMethodFromJSONTyped(json, false);
}

export function RmaRefundMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RmaRefundMethod {
    return json as RmaRefundMethod;
}

export function RmaRefundMethodToJSON(value?: RmaRefundMethod | null): any {
    return value as any;
}

