/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
*  - ITEMS: gross discount items amount.  - ITEMS_DISCOUNTED: discounted items amount.  - DISCOUNT: discount amount. It is a NEGATIVE amount.
*/
export enum OrderDataSubtotalCode {
    Unknown = 'UNKNOWN',
    Payment = 'PAYMENT',
    Shipment = 'SHIPMENT',
    Tax = 'TAX',
    Items = 'ITEMS',
    ItemsDiscounted = 'ITEMS_DISCOUNTED',
    Discount = 'DISCOUNT'
}
