/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RmaReturnResponse } from '../models/RmaReturnResponse';
import { HttpFile } from '../http/http';

export class RmaListReturnsResponse {
    'returns'?: Array<RmaReturnResponse>;
    'nextPageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "returns",
            "baseName": "returns",
            "type": "Array<RmaReturnResponse>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "nextPageToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RmaListReturnsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

