/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RmaNoteResponse } from '../models/RmaNoteResponse';
import { HttpFile } from '../http/http';

export class RmaListNotesByReturnIdResponse {
    'notes'?: Array<RmaNoteResponse>;
    'nextPageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<RmaNoteResponse>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "nextPageToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RmaListNotesByReturnIdResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

