/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderDataSubtotal } from '../models/OrderDataSubtotal';
import { OrderDataTotal } from '../models/OrderDataTotal';
import { RmaCurrency } from '../models/RmaCurrency';
import { RmaOrderDataItem } from '../models/RmaOrderDataItem';
import { HttpFile } from '../http/http';

export class RmaOrderData {
    'createdAt'?: Date;
    'updatedAt'?: Date;
    'grn'?: string;
    'number'?: string;
    'status'?: string;
    'channel'?: string;
    'market'?: string;
    'items'?: Array<RmaOrderDataItem>;
    'currency'?: RmaCurrency;
    'subtotals'?: { [key: string]: OrderDataSubtotal; };
    'totals'?: { [key: string]: OrderDataTotal; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string",
            "format": ""
        },
        {
            "name": "market",
            "baseName": "market",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<RmaOrderDataItem>",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "RmaCurrency",
            "format": ""
        },
        {
            "name": "subtotals",
            "baseName": "subtotals",
            "type": "{ [key: string]: OrderDataSubtotal; }",
            "format": ""
        },
        {
            "name": "totals",
            "baseName": "totals",
            "type": "{ [key: string]: OrderDataTotal; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RmaOrderData.attributeTypeMap;
    }

    public constructor() {
    }
}



