/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RmaReturnProductProperty } from '../models/RmaReturnProductProperty';
import { HttpFile } from '../http/http';

export class RmaReturnProduct {
    'grn'?: string;
    'reason'?: string;
    'requested'?: RmaReturnProductProperty;
    'approved'?: RmaReturnProductProperty;
    'verified'?: RmaReturnProductProperty;
    'refunded'?: RmaReturnProductProperty;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "requested",
            "baseName": "requested",
            "type": "RmaReturnProductProperty",
            "format": ""
        },
        {
            "name": "approved",
            "baseName": "approved",
            "type": "RmaReturnProductProperty",
            "format": ""
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "RmaReturnProductProperty",
            "format": ""
        },
        {
            "name": "refunded",
            "baseName": "refunded",
            "type": "RmaReturnProductProperty",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RmaReturnProduct.attributeTypeMap;
    }

    public constructor() {
    }
}

