/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum RmaRefundMethod {
    Unknown = 'REFUND_METHOD_UNKNOWN',
    Offline = 'REFUND_METHOD_OFFLINE',
    Coupon = 'REFUND_METHOD_COUPON',
    SameAsPayment = 'REFUND_METHOD_SAME_AS_PAYMENT'
}
