/**
 * RMA Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RmaSetReceivedItemsRequestItem } from '../models/RmaSetReceivedItemsRequestItem';
import { HttpFile } from '../http/http';

export class RmaSetReceivedItemsRequest {
    'tenantId': string;
    'id': string;
    'items': Array<RmaSetReceivedItemsRequestItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<RmaSetReceivedItemsRequestItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RmaSetReceivedItemsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

